services:
  mssql-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: samahesab-db
    image: samahesab-db:latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SamaHesab@2024"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - samahesab-data:/var/opt/mssql
    restart: unless-stopped

volumes:
  samahesab-data:
    driver: local
